In [3]:
import pandas as pd

## 파일 읽기
total_temp = pd.read_csv('C:/skn24/2601_mini_team/EDA_MINI_1TEAM/jaehoon/미니프로젝트/data/weather_data_201501_202412.csv',encoding='CP949')
total_temp.info()
total_temp.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11423 entries, 0 to 11422
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   지점                  11423 non-null  int64
 1   지점명                 11423 non-null  object
 2   일시                  11423 non-null  object
 3   평균기온(°C)            11415 non-null  float64
 4   평균현지기압(hPa)         11415 non-null  float64
 5   평균해면기압(hPa)         11415 non-null  float64
 6   평균수증기압(hPa)         11413 non-null  float64
 7   평균상대습도(%)           11413 non-null  float64
 8   월합강수량(00~24h만)(mm)  11411 non-null  float64
 9   평균풍속(m/s)           11403 non-null  float64
 10  일조율(%)              11419 non-null  float64
 11  최심적설(cm)            596 non-null    float64
 12  평균지면온도(°C)          11400 non-null  float64
dtypes: float64(10), int64(1), object(2)
memory usage: 1.1+ MB

,지점,평균기온(°C),평균현지기압(hPa),평균해면기압(hPa),평균수증기압(hPa),평균상대습도(%),월합강수량(00~24h만)(mm),평균풍속(m/s),일조율(%),최심적설(cm),평균지면온도(°C)
count,11423.000000,11415.000000,11415.000000,11415.000000,11413.000000,11413.000000,11411.000000,11403.000000,11419.000000,596.000000,11400.000000
mean,197.425282,13.478563,1004.005283,1016.453850,12.948138,69.643564,110.337709,1.958493,51.930762,7.075000,15.643395
std,64.245690,9.132526,15.979862,6.703078,8.173073,10.922087,115.812094,0.988665,11.991296,13.866678,10.342618
min,90.000000,-8.500000,920.500000,1003.800000,2.100000,32.000000,0.000000,0.500000,0.400000,0.000000,-6.200000
25%,136.000000,5.700000,998.800000,1009.300000,5.900000,62.000000,31.600000,1.300000,44.110000,1.200000,6.300000
50%,202.000000,14.000000,1006.500000,1017.500000,10.700000,71.000000,74.200000,1.700000,53.250000,3.400000,16.200000
75%,258.000000,21.800000,1014.400000,1022.700000,19.500000,78.000000,148.200000,2.300000,60.885000,6.700000,25.200000
max,296.000000,29.900000,1026.500000,1028.400000,34.800000,99.000000,947.400000,10.000000,104.490000,162.800000,36.600000

In [2]:
total_temp.isna().sum()

지점                        0
지점명                       0
일시                        0
평균기온(°C)                  8
평균현지기압(hPa)               8
평균해면기압(hPa)               8
평균수증기압(hPa)              10
평균상대습도(%)                10
월합강수량(00~24h만)(mm)       12
평균풍속(m/s)                20
일조율(%)                    4
최심적설(cm)              10827
평균지면온도(°C)               23
dtype: int64

In [4]:
total_temp['최심적설(cm)'] = total_temp['최심적설(cm)'].fillna(0)
total_temp = total_temp.dropna()
print( total_temp.isna().sum())

# 결측치 지역-월을 찾고 평균으로 na값 채움
# 연도 / 월 쪼개기 = 나중에 보여주는 목적에 따라 groupby
total_temp['years'] = total_temp['일시'].str.split('-').str[0].astype(int)
total_temp['month'] = total_temp['일시'].str.split('-').str[1].astype(int)
total_temp['HDD'] = (18 - total_temp['평균기온(°C)']).clip(lower=0)
total_temp['CDD'] = (total_temp['평균기온(°C)'] - 24).clip(lower=0)

지점                    0
지점명                   0
일시                    0
평균기온(°C)              0
평균현지기압(hPa)           0
평균해면기압(hPa)           0
평균수증기압(hPa)           0
평균상대습도(%)             0
월합강수량(00~24h만)(mm)    0
평균풍속(m/s)             0
일조율(%)                0
최심적설(cm)              0
평균지면온도(°C)            0
dtype: int64

In [7]:
total_temp['지점명'].unique()

array(['속초', '북춘천', '철원', '동두천', '파주', '대관령', '춘천', '백령도', '북강릉', '강릉',
       '동해', '서울', '인천', '원주', '울릉도', '수원', '영월', '충주', '서산', '울진', '청주',
       '대전', '추풍령', '안동', '상주', '포항', '군산', '대구', '전주', '울산', '창원', '광주',
       '부산', '통영', '목포', '여수', '흑산도', '완도', '고창', '순천', '진도(첨찰산)',
       '대구(기)', '홍성', '서청주', '제주', '고산', '성산', '서귀포', '진주', '강화', '양평',
       '이천', '인제', '홍천', '태백', '정선군', '제천', '보은', '천안', '보령', '부여', '금산',
       '세종', '부안', '임실', '정읍', '남원', '장수', '고창군', '영광군', '김해시', '순창군',
       '북창원', '양산시', '보성군', '강진군', '장흥', '해남', '고흥', '의령군', '함양군', '광양시',
       '진도군', '봉화', '영주', '문경', '청송군', '영덕', '의성', '구미', '영천', '경주시',
       '거창', '합천', '밀양', '산청', '거제', '남해', '북부산'], dtype=object)

In [8]:
chung = [
    "천안", "아산", "서산", "당진", "공주", "보령", "논산", "계룡",
    "홍성", "예산", "태안", "금산", "부여", "서천", "청양", "청주", "충주", "제천",
    "보은", "옥천", "영동", "괴산", "음성", "단양", "증평", "진천","대전", '세종'
]

In [9]:
# 전체 강원도 지역 중 기상청에서 수집한 강원도 기상 측정 지역 확인 (9개)
chung_list = []
for i in total_temp['지점명'].drop_duplicates(): 
    if i in chung:
        chung_list.append(i)
chung_list

['충주', '서산', '청주', '대전', '홍성', '제천', '보은', '천안', '보령', '부여', '금산', '세종']

In [ ]:
# 강원도 지역의 속한 데이터프레임 뽑기 
chung_keyword = "|".join(chung_list)
chung_total = total_temp[total_temp['지점명'].str.contains(chung_keyword)].reset_index(drop=True)
chung_total
chung_total.to_csv('C:/skn24/2601_mini_team/EDA_MINI_1TEAM/jaehoon/미니프로젝트/data/preprocessing/충청도 데이터/chung_temp.csv')

In [6]:
gangwon_total

,지점,지점명,일시,평균기온(°C),평균현지기압(hPa),평균해면기압(hPa),평균수증기압(hPa),평균상대습도(%),월합강수량(00~24h만)(mm),평균풍속(m/s),일조율(%),최심적설(cm),평균지면온도(°C),years,month,HDD,CDD
0,90,속초,2015-01,1.8,1019.8,1022.1,3.7,52.0,8.7,2.2,60.79,3.0,1.2,2015,1,16.2,0.0
1,90,속초,2015-02,2.4,1018.0,1020.2,4.4,59.0,32.1,2.5,62.81,8.7,2.3,2015,2,15.6,0.0
2,90,속초,2015-03,6.6,1017.0,1019.2,5.2,52.0,8.0,2.5,74.49,0.0,8.5,2015,3,11.4,0.0
3,90,속초,2015-04,11.1,1014.0,1016.2,8.1,69.0,74.2,2.5,46.87,0.0,12.8,2015,4,6.9,0.0
4,90,속초,2015-05,17.8,1005.8,1007.9,11.5,61.0,9.2,2.4,67.60,0.0,23.7,2015,5,0.2,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1290,212,홍천,2024-08,27.5,992.0,1007.7,27.9,78.0,106.9,1.0,51.33,0.0,30.6,2024,8,0.0,3.5
1291,212,홍천,2024-09,23.1,998.1,1014.1,22.4,80.0,171.4,0.9,39.33,0.0,25.8,2024,9,0.0,0.0
1292,212,홍천,2024-10,14.1,1004.4,1021.1,12.9,81.0,106.2,0.7,32.96,0.0,16.7,2024,10,3.9,0.0
1293,212,홍천,2024-11,7.2,1005.6,1022.9,7.8,75.0,43.3,0.6,45.85,0.0,7.9,2024,11,10.8,0.0
1294,212,홍천,2024-12,-1.9,1006.4,1024.2,3.4,65.0,2.4,0.8,46.63,0.0,-1.8,2024,12,19.9,0.0