In [15]:
import pandas as pd


test = pd.read_csv('C:/skn24/2601_mini_team/EDA_MINI_1TEAM/jaehoon/미니프로젝트/data/preprocessing/충청도 데이터/합 계_total_elect.csv',encoding='CP949')
test
# test.loc[test['시도'] == '대전광역시', '시군구'] = (
#     test.loc[test['시도'] == '대전광역시', '시군구']
#         .str.replace('^(동구|중구|서구|대덕구|유성구)$', '대전', regex=True)
# )
test

      years       시도  시군구 계약종별 지점명  month        전력량
0      2017    대전광역시   대전  합 계   동      1   86569098
1      2017    대전광역시   대전  합 계   중      1   94753039
2      2017    대전광역시   대전  합 계   서      1  168864617
3      2017    대전광역시   대전  합 계  대덕      1  241275329
4      2017    대전광역시   대전  합 계  유성      1  257067038
...     ...      ...  ...  ...  ..    ...        ...
3883   2024     충청남도  홍성군  합 계  홍성     12   93794622
3884   2024     충청남도  예산군  합 계  예산     12  121103055
3885   2024     충청남도  당진시  합 계  당진     12  545077410
3886   2024     충청남도  태안군  합 계  태안     12   78493279
3887   2024  세종특별자치시  세종시  합 계  세종     12  347879157

[3888 rows x 7 columns]

In [16]:
import pandas as pd
import glob

file_path = 'C:/skn24/2601_mini_team/EDA_MINI_1TEAM/jaehoon/미니프로젝트/data/preprocessing/충청도 데이터/*.csv'
file_glob = glob.glob(file_path)

contract_list = [pd.read_csv(file,encoding='CP949') for file in file_glob]
chung_temp = pd.read_csv('C:/skn24/2601_mini_team/EDA_MINI_1TEAM/jaehoon/미니프로젝트/data/preprocessing/충청도 데이터/온도/chung_temp.csv',encoding='utf-8')
chung_temp['지점명'].unique()

array(['충주', '서산', '청주', '대전', '홍성', '서청주', '제천', '보은', '천안', '보령', '부여',
       '금산', '세종'], dtype=object)

In [17]:
# 계약종별 날씨, 전력 데이터 merge 저장
for i in contract_list:
    chung_merge = pd.merge(chung_temp,i,left_on=['years','지점명','month'], right_on = ['years','지점명','month'],how='inner')
    chung_merge = chung_merge.drop_duplicates()
    #결측치 포함 열 제거 
    chung_merge = chung_merge.dropna(how='any',axis=1)
    file_name = chung_merge['계약종별'].unique()[0]
    chung_merge.to_csv(f'C:/skn24/2601_mini_team/EDA_MINI_1TEAM/jaehoon/미니프로젝트/data/preprocessing/충청도 데이터/머지/{file_name}_elect_temp_gangwon.csv')

In [19]:
chung_merge

,Unnamed: 0,지점,지점명,일시,평균기온(°C),평균현지기압(hPa),평균해면기압(hPa),평균수증기압(hPa),평균상대습도(%),월합강수량(00~24h만)(mm),...,최심적설(cm),평균지면온도(°C),years,month,HDD,CDD,시도,시군구,계약종별,전력량
0,0,127,충주,2015-01,-1.7,1010.3,1024.9,3.8,66.0,15.6,...,0.0,-0.4,2015,1,19.7,0.0,충청북도,충주시,합 계,221971909
1,1,127,충주,2015-02,0.6,1008.0,1022.6,3.9,59.0,22.8,...,0.0,2.0,2015,2,17.4,0.0,충청북도,충주시,합 계,203888927
2,2,127,충주,2015-03,5.6,1007.2,1021.4,4.0,45.0,31.7,...,0.0,5.7,2015,3,12.4,0.0,충청북도,충주시,합 계,192231835
3,3,127,충주,2015-04,12.5,1002.5,1016.3,8.1,59.0,88.9,...,0.0,12.9,2015,4,5.5,0.0,충청북도,충주시,합 계,181247748
4,4,127,충주,2015-05,18.5,996.4,1009.8,10.6,53.0,23.0,...,0.0,21.7,2015,5,0.0,0.0,충청북도,충주시,합 계,162132495
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1250,1390,239,세종,2024-08,28.1,996.9,1006.9,29.3,78.0,70.7,...,0.0,32.7,2024,8,0.0,4.1,세종특별자치시,세종시,합 계,388731688
1251,1391,239,세종,2024-09,25.2,1002.4,1012.6,24.6,77.0,232.1,...,0.0,29.1,2024,9,0.0,1.2,세종특별자치시,세종시,합 계,388261989
1252,1392,239,세종,2024-10,15.7,1009.3,1019.9,14.7,83.0,97.1,...,0.0,17.7,2024,10,2.3,0.0,세종특별자치시,세종시,합 계,345625013
1253,1393,239,세종,2024-11,9.5,1011.1,1022.1,8.8,72.0,43.1,...,0.0,9.6,2024,11,8.5,0.0,세종특별자치시,세종시,합 계,324968355
1254,1394,239,세종,2024-12,1.3,1012.7,1024.0,4.6,67.0,6.0,...,0.0,1.1,2024,12,16.7,0.0,세종특별자치시,세종시,합 계,347879157